service: toxic-catalogo-interactivo

plugins:
    - serverless-deployment-bucket
    - fullstack-serverless

custom:
    stage: ${opt:stage, 'prod'}
    prefix: ${self:service}-${self:custom.stage}
    fullstack:
        domain: catalogo.toxicshine.com.ar
        certificate: arn:aws:acm:us-east-1:404318849113:certificate/2c6c9a7b-17b3-4710-8e6f-b276787d026f
        distributionFolder: dist
        bucketName: catalog-bucket
        indexDocument: index.html
        errorDocument: error.html
        singlePageApp: true
        invalidationPaths:
            - /
        compressWebContent: true
        minimumProtocolVersion: TLSv1.2_2018
        priceClass: PriceClass_100
        noConfirm: true

provider:
    name: aws
    region: us-east-1
    stackName: ${self:custom.prefix}-stack
    runtime: nodejs20.x
    deploymentBucket:
        name: ${self:custom.prefix}-serverless
